function [Matrices]=C_build_out_matrices(A,A_no_bc,M,M_no_bc,b,b_no_bc,u_g)
%% function [Matrices]=C_build_out_matrices(A,A_no_bc,M,M_no_bc,b,b_no_bc,u_g)
%============================================================================
% Store matrices and vactor in the struct Matrices
%============================================================================

Matrices = struct('A',A,...
                'M',M,...
                'b',b,...
                'A_no_bc',A_no_bc,...
                'M_no_bc',M_no_bc,...
                'b_no_bc',b_no_bc,...
                'u_g',u_g);